import merge from 'lodash/merge.js';
import {
	accordion,
	alert,
	article,
	badge,
	background,
	breadcrumb,
	button,
	card,
	close,
	column,
	comment,
	descriptionList,
	divider,
	dotnav,
	dropbar,
	dropdown,
	extensions,
	formRange,
	form,
	grid,
	heading,
	icon,
	iconnav,
	label,
	lightbox,
	link,
	list,
	margin,
	marker,
	modal,
	nav,
	navbar,
	notification,
	offcanvas,
	padding,
	pagination,
	placeholder,
	position,
	progress,
	search,
	section,
	slidenav,
	stepper,
	subnav,
	switcher,
	tab,
	table,
	text,
	tile,
	tooltip,
	utility
} from './components/index.js';
import type { OptionsType } from '$lib/shadcn-ui/preset-types.js';

export default (options: OptionsType = {}) => {
	const defaultHooks = {
		accordion: accordion(),
		alert: alert(),
		// align: {},
		animation: {},
		article: article(),
		background: background(),
		badge: badge(),
		breadcrumb: breadcrumb(),
		button: button(),
		card: card(),
		close: close(),
		column: column(),
		comment: comment(),
		// container: {},
		// countdown: {},
		// cover: {},
		'description-list': descriptionList(),
		divider: divider(options),
		dotnav: dotnav(),
		// drop: {},
		dropbar: dropbar(),
		dropdown: dropdown(),
		// dropnav: {},
		extensions: extensions(options),
		// flex: {},
		'form-range': formRange(),
		form: form(options),
		grid: grid(),
		heading: heading(),
		// height: {},
		icon: icon(),
		iconnav: iconnav(),
		label: label(),
		// leader: {},
		lightbox: lightbox(),
		link: link(),
		list: list(),
		margin: margin(),
		marker: marker(),
		modal: modal(),
		nav: nav(),
		navbar: navbar(),
		notification: notification(),
		offcanvas: offcanvas(),
		// overlay: {},
		padding: padding(),
		pagination: pagination(),
		placeholder: placeholder(),
		position: position(),
		progress: progress(),
		search: search(),
		section: section(),
		slidenav: slidenav(),
		// slider: {},
		// slideshow: {},
		// sortable: {},
		// spinner: {},
		stepper: stepper(options),
		// sticky: {},
		subnav: subnav(),
		// svg: {},
		switcher: switcher(),
		tab: tab(),
		table: table(),
		text: text(),
		// thumbnav: {},
		tile: tile(),
		tooltip: tooltip(),
		// totop: {},
		// transition: {},
		utility: utility()
		// visibility: {},
		// width: {},
		// print: {},
	};

	return merge({}, defaultHooks, options.overrides);
};
